Models/ErrorViewModel.cs
using System;

namespace Bandomoji_uzduotis.Models
{
    public class ErrorViewModel
    {
        public string RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

Models/Filmas.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using System.ComponentModel.DataAnnotations;

namespace Bandomoji_uzduotis.Models
{
    public class Filmas
    {
        [Key]
        public int ID { get; set; }
        public string Pavadinimas { get; set; }
        [DataType(DataType.Date)]
        public DateTime IsleidimoData { get; set; }
        public Zanras FilmoZanras { get; set; }
    }
}

Models/Zanras.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace Bandomoji_uzduotis.Models
{
    public enum Zanras
    {
        Drama = 1,
        Detektyvas = 2,
        Komedija = 3,
        Nuotykiu = 4,
        Siaubo = 5,
        Veiksmo = 6
    }
}

Controllers/FilmasController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using System.Data.SqlClient;
using Bandomoji_uzduotis.Data;
using Bandomoji_uzduotis.Models;

namespace Bandomoji_uzduotis.Controllers
{
    public class FilmasController : Controller
    {
        private readonly ApplicationDbContext _context;

        public FilmasController(ApplicationDbContext context)
        {
            _context = context;
        }

        // GET: Filmas

        public async Task<IActionResult> Index(string searchString, int? pageCount)
        {
            if (!String.IsNullOrEmpty(searchString))
            {
                ViewBag.CurrentString = searchString;
            }
            
            if (pageCount != null)
            {
                ViewBag.PageNumber = pageCount;
            }
            else if (ViewBag.PageNumber == null)
            {
                ViewBag.PageNumber = 1;
            }
            ViewBag.Count = _context.Filmas.FromSqlRaw("SELECT * FROM Filmas WHERE Pavadinimas LIKE '%" + (string)ViewBag.CurrentString + "%' ").Count();
            return View(await _context.Filmas.FromSqlRaw("SELECT * FROM Filmas WHERE Pavadinimas LIKE '%" + (string)ViewBag.CurrentString + "%' " +
                "ORDER BY Pavadinimas OFFSET " + (10 * ((int)ViewBag.PageNumber - 1) + "ROWS FETCH NEXT 10 ROWS ONLY").ToString()).ToListAsync());
        }

        // GET: Filmas/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var filmas = await _context.Filmas
                .FirstOrDefaultAsync(m => m.ID == id);
            if (filmas == null)
            {
                return NotFound();
            }

            return View(filmas);
        }

        // GET: Filmas/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: Filmas/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("ID,Pavadinimas,IsleidimoData,FilmoZanras")] Filmas filmas)
        {
            if (ModelState.IsValid)
            {
                _context.Add(filmas);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(filmas);
        }

        // GET: Filmas/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var filmas = await _context.Filmas.FindAsync(id);
            if (filmas == null)
            {
                return NotFound();
            }
            return View(filmas);
        }

        // POST: Filmas/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("ID,Pavadinimas,IsleidimoData,FilmoZanras")] Filmas filmas)
        {
            if (id != filmas.ID)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(filmas);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!FilmasExists(filmas.ID))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(filmas);
        }

        // GET: Filmas/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var filmas = await _context.Filmas
                .FirstOrDefaultAsync(m => m.ID == id);
            if (filmas == null)
            {
                return NotFound();
            }

            return View(filmas);
        }

        // POST: Filmas/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var filmas = await _context.Filmas.FindAsync(id);
            _context.Filmas.Remove(filmas);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool FilmasExists(int id)
        {
            return _context.Filmas.Any(e => e.ID == id);
        }
    }
}

Controllers/HomeController.cs
using Bandomoji_uzduotis.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;

namespace Bandomoji_uzduotis.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        public IActionResult List()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

Views/Filmas/Create.cshtml
@model Bandomoji_uzduotis.Models.Filmas

@{
    ViewData["Title"] = "Sukurti";
}

<h1>Sukurti</h1>

<h4>Filmas</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="Pavadinimas" class="control-label"></label>
                <input asp-for="Pavadinimas" class="form-control" />
                <span asp-validation-for="Pavadinimas" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="IsleidimoData" class="control-label"></label>
                <input asp-for="IsleidimoData" class="form-control" />
                <span asp-validation-for="IsleidimoData" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="FilmoZanras" class="control-label"></label>
                <select asp-for="FilmoZanras" asp-items="@Html.GetEnumSelectList(typeof(Zanras))" class="form-control"></select>
                <span asp-validation-for="FilmoZanras" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Sukurti" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Grįžti atgal</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

Views/Filmas/Delete.cshtml
@model Bandomoji_uzduotis.Models.Filmas

@{
    ViewData["Title"] = "Pašalinti";
}

<h1>Pašalinti</h1>

<h3>Ar jūs tikrai norite pašalinti šį filmą?</h3>
<div>
    <h4>Filmas</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Pavadinimas)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Pavadinimas)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.IsleidimoData)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.IsleidimoData)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.FilmoZanras)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.FilmoZanras)
        </dd>
    </dl>
    
    <form asp-action="Delete">
        <input type="hidden" asp-for="ID" />
        <input type="submit" value="Pašalinti" class="btn btn-danger" /> |
        <a asp-action="Index">Grįžti atgal</a>
    </form>
</div>

Views/Filmas/Details.cshtml
@model Bandomoji_uzduotis.Models.Filmas

@{
    ViewData["Title"] = "Detalės";
}

<h1>Detalės</h1>

<div>
    <h4>Filmas</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Pavadinimas)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Pavadinimas)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.IsleidimoData)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.IsleidimoData)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.FilmoZanras)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.FilmoZanras)
        </dd>
    </dl>
</div>
<div>
    <a asp-action="Edit" asp-route-id="@Model.ID">Redaguoti</a> |
    <a asp-action="Index">Grįžti atgal</a>
</div>

Views/Filmas/Edit.cshtml
@model Bandomoji_uzduotis.Models.Filmas

@{
    ViewData["Title"] = "Redaguoti";
}

<h1>Redaguoti</h1>

<h4>Filmas</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="ID" />
            <div class="form-group">
                <label asp-for="Pavadinimas" class="control-label"></label>
                <input asp-for="Pavadinimas" class="form-control" />
                <span asp-validation-for="Pavadinimas" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="IsleidimoData" class="control-label"></label>
                <input asp-for="IsleidimoData" class="form-control" />
                <span asp-validation-for="IsleidimoData" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="FilmoZanras" class="control-label"></label>
                <select asp-for="FilmoZanras" asp-items="@Html.GetEnumSelectList(typeof(Zanras))" class="form-control"></select>
                <span asp-validation-for="FilmoZanras" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Saugoti" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <input type="hidden" name="searchString" />
    <a asp-action="Index">Grįžti atgal</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

Views/Filmas/Index.cshtml
@model IEnumerable<Bandomoji_uzduotis.Models.Filmas>

@{
    ViewData["Title"] = "Turinys";
}

<h1>Turinys</h1>




<form asp-action="Index">
    <a asp-action="Create">Sukurti naują</a>
    <div style="text-align:right" class="form-group">
        <input type="text" name="searchString" value=@ViewBag.CurrentString />
        <input type="submit" value="Ieškoti" class="btn btn-primary" />
    </div>
</form>
<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.Pavadinimas)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.IsleidimoData)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.FilmoZanras)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
        @foreach (var item in Model)
        {
            <tr>
                <td>
                    @Html.DisplayFor(modelItem => item.Pavadinimas)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.IsleidimoData)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.FilmoZanras)
                </td>
                <td>
                    <a asp-action="Edit" asp-route-id="@item.ID">Redaguoti</a> |
                    <a asp-action="Details" asp-route-id="@item.ID">Detalės</a> |
                    <a asp-action="Delete" asp-route-id="@item.ID">Pašalinti</a>
                </td>
            </tr>
        }
    </tbody>
</table>

@{int maxPage = (int)Math.Ceiling((double)ViewBag.Count / 10);
}

<button class="btn btn-primary" onclick="location.href='@Url.Action("Index", "Filmas", new { pageCount = Math.Max(1, ViewBag.PageNumber - 1), searchString = ViewBag.CurrentString })';return false;"><</button>  <input type="number" id="MaxPage" name="MaxPage" value=@maxPage readonly /> / <input type="number" id="pageCount" name="pageCount" value=@ViewBag.PageNumber readonly /> <button class="btn btn-primary" onclick="location.href='@Url.Action("Index", "Filmas", new { pageCount = Math.Min(maxPage, ViewBag.PageNumber + 1), searchString = ViewBag.CurrentString })';return false;">></button>


<script>
    function PageUp() {
        $maxpage = document.getElementById("MaxPage").value;
        $currentpage = document.getElementById("PageCount").value;
        if ($maxpage != $currentpage) {
            document.getElementById("PageCount").value = Number($currentpage) + 1;
            document.getElementById("PageChange").submit();
        }
    }
</script>

Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <p>Learn about <a href="https://docs.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
</div>

Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Bandomoji_uzduotis</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">Bandomoji_uzduotis</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse">
                    <!-- <partial name="_LoginPartial" /> -->
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Pagrindinis</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Filmas" asp-action="Index">Filmai</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privatumas</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2021 - Bandomoji_uzduotis - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privatumas</a>
        </div>
    </footer>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @RenderSection("Scripts", required: false)
</body>
</html>